name: IslandUpgrade
version: 2.0.0
main: com.skyblock.upgrade.IslandUpgradePlugin
api-version: 1.19
author: SkyBlock Team
description: SQLite-based BentoBox BSkyBlock upgrade system
depend: [BentoBox, Vault, PlaceholderAPI]
softdepend: [DeluxeMenus]

commands:
  islandupgrade:
    description: Manage island upgrades
    usage: /islandupgrade <border|member|piston|reload|info>
    aliases: [iu, adayukseltme, yukseltme]

permissions:
  islandupgrade.admin:
    description: Admin permissions
    default: op
  islandupgrade.use:
    description: Use upgrades
    default: true
