name: IslandUpgrade
version: 1.0.0
main: com.skyblock.upgrade.IslandUpgradePlugin
api-version: 1.19
author: YourName
description: BentoBox BSkyBlock upgrade system
depend: [BentoBox, Vault, PlaceholderAPI]
softdepend: [DeluxeMenus, GeneratorUpgrade]

commands:
  islandupgrade:
    description: Manage island upgrades
    usage: /islandupgrade <border|member|piston|reload>
    aliases: [iu, adayukseltme]

permissions:
  islandupgrade.admin:
    description: Admin permissions for island upgrades
    default: op
  islandupgrade.use:
    description: Use island upgrades
    default: true
